### ISSUE TITLE
Cancelling subscriptions based on HTTP Status codes

### ISSUE THREAD

**Issue by hemm1** [entur/ukur#6]
Hi! I am sorry if this is the wrong place for this type of question. I'd be happy to post it somewhere else if you can point me in the right direction.

We are working on using ukur as the basis for our push messages in the NSB app, and we are experimenting a little with creating subscriptions and comparing the data with the old Hafas backend we have been using previously. In your docs, it says that ukur will cancel a subscription if it receives something else than HTTP Status code 200 four times or if it receives Status code 205. We have tried this in both our test environment and our production environment, and the subscriptions do not seem to be cancelled. See attached screenshot from our access logs in our production environment for a randomly chosen subscription. The screen shot is taken just around the time where we stopped sending 404 and started sending 205. It did not seem to make a difference.

![image](https://user-images.githubusercontent.com/3276739/50290529-414c2880-046c-11e9-87c7-9dc66d3e8855.png)

Is this a known issue, or are we perhaps doing something wrong or misunderstanding something? Any help would be greatly appreciated 😄

**Comment by assadriaz** [comment]
And for your logs and comment above it looks like you are posting sending different codes to ukur, but isn't it other way around , a client e.g. nsb subscribe to uker and uker push subscription related message to client and expect 200 response

**Comment by hemm1** [comment]
Hi, thanks for your reply!

I am sorry, I should have been clearer about what my screenshot was. It is from our access logs and shows some of the requests we are receiving from ukur for one randomly chosen subscription. The status codes (404 and 205) are what _we_ are sending as a response to ukur. As you can see, we are first sending 404 response, but the requests from ukur does not stop. Later, we switch to sending 205 response, but the requests still keep on coming. As far as I can understand the ukur documentation, the subscription in ukur should either stop after we respond four times in a row with a 404 status code, or after we respond once with a 205 status code. Neither of these seem to be true. Relevant ukur docs are here: https://github.com/entur/ukur/blob/master/functional_description.md#terminate-a-subscription

Am I misunderstanding something here? I would rather not have to loop through "dead" subscriptions and terminate them from our side.

**Comment by assadriaz** [comment]
Hi,
I have looked into our logs for corresponding entries with above mentioned screenshot didn't find any related entries at this time period.
<img width="1412" alt="screenshot 2018-12-21 at 10 51 55" src="https://user-images.githubusercontent.com/25320434/50336756-372f3600-050f-11e9-8f2f-652afc85aca2.png">

As you can see from logs ,we only received some 205 at 15:24(-1h) and subscriptions were terminated.

**Comment by hemm1** [comment]
Hi again,

Okay, I think I am starting to make some sense of this. I had assumed we only made one subscription in ukur for each UUID. That seems to not be the case. I have to do a little digging on this on our side.

Also, the reason you didn't find the related entries from the time i posted was that they were heartbeat requests. Am I right in assuming that several 404 responses or a 205 response has no effect on a heartbeat response?
